### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_jayg_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@J-M-C-V @gleyder-18 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora Derly y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/93795520-196c9480-fbff-11ea-9f3d-aaccda3d1e28.png)

**Comment by J-M-C-V** [comment]
[Modelo entidad relacion.docx](https://github.com/JohnFlorez25/equipo8_jayg_ppi2020/files/5435789/Modelo.entidad.relacion.docx)

**Comment by JohnFlorez25** [comment]
@J-M-C-V @gleyder-18 debe colocar esta información en la wiki
