### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_jayg_ppi2020#2]

**Comment by J-M-C-V** [comment]
[Diagrama de pescado.docx](https://github.com/JohnFlorez25/equipo8_jayg_ppi2020/files/5435877/Diagrama.de.pescado.docx)

**Comment by J-M-C-V** [comment]
[Uploading semana2.pptx…]()

**Comment by JohnFlorez25** [comment]
@J-M-C-V @gleyder-18 debe colocar esta información en la wiki
