### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_jayg_ppi2020#8]

**Comment by J-M-C-V** [comment]
[Semana 5.pptx](https://github.com/JohnFlorez25/equipo8_jayg_ppi2020/files/5435958/Semana.5.pptx)

**Comment by JohnFlorez25** [comment]
@J-M-C-V @gleyder-18 debe colocar esta información en la wiki
